export interface MedicationCatalogItem {
  name: string;
  presentations: string[];
  therapeuticGroup: string;
}

const baseMedicationCatalogSeed: MedicationCatalogItem[] = [
  { name: "Paracetamol", presentations: ["500 mg tableta", "120 mg/5 mL suspension"], therapeuticGroup: "analgesicos" },
  { name: "Ibuprofeno", presentations: ["400 mg tableta", "100 mg/5 mL suspension"], therapeuticGroup: "analgesicos" },
  { name: "Naproxeno", presentations: ["500 mg tableta"], therapeuticGroup: "analgesicos" },
  { name: "Diclofenaco", presentations: ["50 mg tableta", "75 mg/3 mL ampolla"], therapeuticGroup: "analgesicos" },
  { name: "Ketorolaco", presentations: ["10 mg tableta", "30 mg/mL ampolla"], therapeuticGroup: "analgesicos" },
  { name: "Meloxicam", presentations: ["15 mg tableta", "15 mg/1.5 mL ampolla"], therapeuticGroup: "analgesicos" },
  { name: "Celecoxib", presentations: ["200 mg capsula"], therapeuticGroup: "analgesicos" },
  { name: "Metamizol", presentations: ["500 mg tableta", "1 g/2 mL ampolla"], therapeuticGroup: "analgesicos" },
  { name: "Tramadol", presentations: ["50 mg capsula", "100 mg/2 mL ampolla"], therapeuticGroup: "analgesicos" },
  { name: "Morfina", presentations: ["10 mg/mL ampolla"], therapeuticGroup: "analgesicos" },
  { name: "Fentanilo", presentations: ["0.05 mg/mL ampolla", "25 mcg/h parche"], therapeuticGroup: "analgesicos" },
  { name: "Codeina", presentations: ["30 mg tableta"], therapeuticGroup: "analgesicos" },
  { name: "Oxicodona", presentations: ["10 mg tableta"], therapeuticGroup: "analgesicos" },
  { name: "Buprenorfina", presentations: ["0.3 mg/mL ampolla", "10 mcg/h parche"], therapeuticGroup: "analgesicos" },
  { name: "Lidocaina", presentations: ["2% ampolla", "5% parche"], therapeuticGroup: "anestesicos" },
  { name: "Bupivacaina", presentations: ["0.5% ampolla"], therapeuticGroup: "anestesicos" },
  { name: "Ropivacaina", presentations: ["0.75% ampolla"], therapeuticGroup: "anestesicos" },
  { name: "Pregabalina", presentations: ["75 mg capsula", "150 mg capsula"], therapeuticGroup: "analgesicos" },
  { name: "Gabapentina", presentations: ["300 mg capsula"], therapeuticGroup: "analgesicos" },
  { name: "Amitriptilina", presentations: ["25 mg tableta"], therapeuticGroup: "neurologicos" },

  { name: "Acido acetilsalicilico", presentations: ["100 mg tableta", "500 mg tableta"], therapeuticGroup: "cardiovasculares" },
  { name: "Clopidogrel", presentations: ["75 mg tableta"], therapeuticGroup: "cardiovasculares" },
  { name: "Ticagrelor", presentations: ["90 mg tableta"], therapeuticGroup: "cardiovasculares" },
  { name: "Prasugrel", presentations: ["10 mg tableta"], therapeuticGroup: "cardiovasculares" },
  { name: "Warfarina", presentations: ["5 mg tableta"], therapeuticGroup: "cardiovasculares" },
  { name: "Acenocumarol", presentations: ["4 mg tableta"], therapeuticGroup: "cardiovasculares" },
  { name: "Apixaban", presentations: ["5 mg tableta", "2.5 mg tableta"], therapeuticGroup: "cardiovasculares" },
  { name: "Rivaroxaban", presentations: ["20 mg tableta", "10 mg tableta"], therapeuticGroup: "cardiovasculares" },
  { name: "Dabigatran", presentations: ["150 mg capsula"], therapeuticGroup: "cardiovasculares" },
  { name: "Enoxaparina", presentations: ["40 mg/0.4 mL jeringa", "60 mg/0.6 mL jeringa"], therapeuticGroup: "cardiovasculares" },
  { name: "Heparina sodica", presentations: ["5000 UI/mL ampolla"], therapeuticGroup: "cardiovasculares" },
  { name: "Fondaparinux", presentations: ["2.5 mg/0.5 mL jeringa"], therapeuticGroup: "cardiovasculares" },
  { name: "Nitroglicerina", presentations: ["0.5 mg tableta sublingual", "50 mg/10 mL infusion"], therapeuticGroup: "cardiovasculares" },
  { name: "Dinitrato de isosorbide", presentations: ["10 mg tableta sublingual"], therapeuticGroup: "cardiovasculares" },
  { name: "Mononitrato de isosorbide", presentations: ["20 mg tableta"], therapeuticGroup: "cardiovasculares" },
  { name: "Atorvastatina", presentations: ["20 mg tableta", "40 mg tableta"], therapeuticGroup: "cardiovasculares" },
  { name: "Rosuvastatina", presentations: ["20 mg tableta"], therapeuticGroup: "cardiovasculares" },
  { name: "Simvastatina", presentations: ["20 mg tableta"], therapeuticGroup: "cardiovasculares" },
  { name: "Ezetimiba", presentations: ["10 mg tableta"], therapeuticGroup: "cardiovasculares" },
  { name: "Fenofibrato", presentations: ["160 mg tableta"], therapeuticGroup: "cardiovasculares" },

  { name: "Losartan", presentations: ["50 mg tableta", "100 mg tableta"], therapeuticGroup: "cardiovasculares" },
  { name: "Valsartan", presentations: ["160 mg tableta"], therapeuticGroup: "cardiovasculares" },
  { name: "Candesartan", presentations: ["16 mg tableta"], therapeuticGroup: "cardiovasculares" },
  { name: "Enalapril", presentations: ["10 mg tableta", "20 mg tableta"], therapeuticGroup: "cardiovasculares" },
  { name: "Lisinopril", presentations: ["20 mg tableta"], therapeuticGroup: "cardiovasculares" },
  { name: "Captopril", presentations: ["25 mg tableta"], therapeuticGroup: "cardiovasculares" },
  { name: "Perindopril", presentations: ["5 mg tableta"], therapeuticGroup: "cardiovasculares" },
  { name: "Amlodipino", presentations: ["5 mg tableta", "10 mg tableta"], therapeuticGroup: "cardiovasculares" },
  { name: "Nifedipino", presentations: ["30 mg liberacion prolongada"], therapeuticGroup: "cardiovasculares" },
  { name: "Verapamilo", presentations: ["80 mg tableta"], therapeuticGroup: "cardiovasculares" },
  { name: "Diltiazem", presentations: ["60 mg tableta"], therapeuticGroup: "cardiovasculares" },
  { name: "Hidralazina", presentations: ["50 mg tableta", "20 mg/mL ampolla"], therapeuticGroup: "cardiovasculares" },
  { name: "Metildopa", presentations: ["250 mg tableta"], therapeuticGroup: "cardiovasculares" },
  { name: "Clonidina", presentations: ["0.15 mg tableta"], therapeuticGroup: "cardiovasculares" },
  { name: "Doxazosina", presentations: ["4 mg tableta"], therapeuticGroup: "cardiovasculares" },
  { name: "Prazosina", presentations: ["1 mg tableta"], therapeuticGroup: "cardiovasculares" },
  { name: "Atenolol", presentations: ["50 mg tableta"], therapeuticGroup: "cardiovasculares" },
  { name: "Metoprolol", presentations: ["50 mg tableta", "5 mg/5 mL ampolla"], therapeuticGroup: "cardiovasculares" },
  { name: "Carvedilol", presentations: ["12.5 mg tableta"], therapeuticGroup: "cardiovasculares" },
  { name: "Propranolol", presentations: ["40 mg tableta", "1 mg/mL ampolla"], therapeuticGroup: "cardiovasculares" },
  { name: "Bisoprolol", presentations: ["5 mg tableta"], therapeuticGroup: "cardiovasculares" },

  { name: "Furosemida", presentations: ["40 mg tableta", "20 mg/2 mL ampolla"], therapeuticGroup: "cardiovasculares" },
  { name: "Hidroclorotiazida", presentations: ["25 mg tableta"], therapeuticGroup: "cardiovasculares" },
  { name: "Espironolactona", presentations: ["25 mg tableta"], therapeuticGroup: "cardiovasculares" },
  { name: "Clortalidona", presentations: ["25 mg tableta"], therapeuticGroup: "cardiovasculares" },
  { name: "Indapamida", presentations: ["1.5 mg tableta"], therapeuticGroup: "cardiovasculares" },
  { name: "Torasemida", presentations: ["10 mg tableta"], therapeuticGroup: "cardiovasculares" },
  { name: "Amiodarona", presentations: ["200 mg tableta", "150 mg/3 mL ampolla"], therapeuticGroup: "cardiovasculares" },
  { name: "Adenosina", presentations: ["6 mg/2 mL ampolla"], therapeuticGroup: "cardiovasculares" },
  { name: "Digoxina", presentations: ["0.25 mg tableta", "0.5 mg/2 mL ampolla"], therapeuticGroup: "cardiovasculares" },
  { name: "Ivabradina", presentations: ["5 mg tableta"], therapeuticGroup: "cardiovasculares" },
  { name: "Sacubitrilo/Valsartan", presentations: ["49/51 mg tableta"], therapeuticGroup: "cardiovasculares" },
  { name: "Empagliflozina", presentations: ["10 mg tableta"], therapeuticGroup: "endocrinos" },
  { name: "Dapagliflozina", presentations: ["10 mg tableta"], therapeuticGroup: "endocrinos" },
  { name: "Canagliflozina", presentations: ["100 mg tableta"], therapeuticGroup: "endocrinos" },
  { name: "Sitagliptina", presentations: ["100 mg tableta"], therapeuticGroup: "endocrinos" },
  { name: "Linagliptina", presentations: ["5 mg tableta"], therapeuticGroup: "endocrinos" },
  { name: "Vildagliptina", presentations: ["50 mg tableta"], therapeuticGroup: "endocrinos" },
  { name: "Metformina", presentations: ["850 mg tableta", "500 mg tableta"], therapeuticGroup: "endocrinos" },
  { name: "Glibenclamida", presentations: ["5 mg tableta"], therapeuticGroup: "endocrinos" },
  { name: "Gliclazida", presentations: ["60 mg liberacion prolongada"], therapeuticGroup: "endocrinos" },
  { name: "Glimepirida", presentations: ["2 mg tableta"], therapeuticGroup: "endocrinos" },

  { name: "Insulina regular", presentations: ["100 UI/mL frasco", "100 UI/mL lapiz"], therapeuticGroup: "endocrinos" },
  { name: "Insulina NPH", presentations: ["100 UI/mL frasco", "100 UI/mL lapiz"], therapeuticGroup: "endocrinos" },
  { name: "Insulina glargina", presentations: ["100 UI/mL lapiz"], therapeuticGroup: "endocrinos" },
  { name: "Insulina detemir", presentations: ["100 UI/mL lapiz"], therapeuticGroup: "endocrinos" },
  { name: "Insulina lispro", presentations: ["100 UI/mL lapiz"], therapeuticGroup: "endocrinos" },
  { name: "Insulina aspart", presentations: ["100 UI/mL lapiz"], therapeuticGroup: "endocrinos" },
  { name: "Levotiroxina", presentations: ["100 mcg tableta", "50 mcg tableta"], therapeuticGroup: "endocrinos" },
  { name: "Metimazol", presentations: ["5 mg tableta"], therapeuticGroup: "endocrinos" },
  { name: "Propiltiouracilo", presentations: ["50 mg tableta"], therapeuticGroup: "endocrinos" },
  { name: "Calcitriol", presentations: ["0.25 mcg capsula"], therapeuticGroup: "endocrinos" },
  { name: "Colecalciferol", presentations: ["1000 UI capsula", "7000 UI/mL gotas"], therapeuticGroup: "endocrinos" },
  { name: "Carbonato de calcio", presentations: ["500 mg tableta"], therapeuticGroup: "suplementos" },
  { name: "Sulfato ferroso", presentations: ["300 mg tableta", "125 mg/5 mL jarabe"], therapeuticGroup: "suplementos" },
  { name: "Acido folico", presentations: ["1 mg tableta", "5 mg tableta"], therapeuticGroup: "suplementos" },
  { name: "Cianocobalamina", presentations: ["1 mg/mL ampolla"], therapeuticGroup: "suplementos" },
  { name: "Tiamina", presentations: ["100 mg tableta", "100 mg/mL ampolla"], therapeuticGroup: "suplementos" },
  { name: "Pyridoxina", presentations: ["50 mg tableta"], therapeuticGroup: "suplementos" },
  { name: "Acido ascorbico", presentations: ["500 mg tableta"], therapeuticGroup: "suplementos" },
  { name: "Zinc sulfato", presentations: ["20 mg tableta"], therapeuticGroup: "suplementos" },
  { name: "Magnesio oxido", presentations: ["400 mg tableta"], therapeuticGroup: "suplementos" },

  { name: "Prednisona", presentations: ["20 mg tableta", "5 mg tableta"], therapeuticGroup: "corticoides" },
  { name: "Prednisolona", presentations: ["5 mg tableta", "15 mg/5 mL solucion"], therapeuticGroup: "corticoides" },
  { name: "Dexametasona", presentations: ["4 mg tableta", "4 mg/mL ampolla"], therapeuticGroup: "corticoides" },
  { name: "Hidrocortisona", presentations: ["100 mg vial", "1% crema"], therapeuticGroup: "corticoides" },
  { name: "Metilprednisolona", presentations: ["500 mg vial", "4 mg tableta"], therapeuticGroup: "corticoides" },
  { name: "Betametasona", presentations: ["4 mg/mL ampolla", "0.05% crema"], therapeuticGroup: "corticoides" },
  { name: "Budesonida", presentations: ["200 mcg inhalador", "0.5 mg/2 mL nebulizacion"], therapeuticGroup: "respiratorios" },
  { name: "Beclometasona", presentations: ["100 mcg inhalador"], therapeuticGroup: "respiratorios" },
  { name: "Fluticasona", presentations: ["125 mcg inhalador", "50 mcg spray nasal"], therapeuticGroup: "respiratorios" },
  { name: "Mometasona", presentations: ["50 mcg spray nasal"], therapeuticGroup: "respiratorios" },
  { name: "Salbutamol", presentations: ["100 mcg inhalador", "5 mg/mL nebulizacion"], therapeuticGroup: "respiratorios" },
  { name: "Levalbuterol", presentations: ["45 mcg inhalador"], therapeuticGroup: "respiratorios" },
  { name: "Ipratropio bromuro", presentations: ["20 mcg inhalador", "0.25 mg/mL nebulizacion"], therapeuticGroup: "respiratorios" },
  { name: "Tiotropio", presentations: ["18 mcg capsula inhalatoria"], therapeuticGroup: "respiratorios" },
  { name: "Formoterol", presentations: ["12 mcg capsula inhalatoria"], therapeuticGroup: "respiratorios" },
  { name: "Salmeterol", presentations: ["25 mcg inhalador"], therapeuticGroup: "respiratorios" },
  { name: "Fluticasona/Salmeterol", presentations: ["125/25 mcg inhalador"], therapeuticGroup: "respiratorios" },
  { name: "Budesonida/Formoterol", presentations: ["160/4.5 mcg inhalador"], therapeuticGroup: "respiratorios" },
  { name: "Montelukast", presentations: ["10 mg tableta", "4 mg sobre"], therapeuticGroup: "respiratorios" },
  { name: "Aminofilina", presentations: ["250 mg/10 mL ampolla"], therapeuticGroup: "respiratorios" },

  { name: "Omeprazol", presentations: ["20 mg capsula", "40 mg vial"], therapeuticGroup: "gastrointestinal" },
  { name: "Pantoprazol", presentations: ["40 mg tableta", "40 mg vial"], therapeuticGroup: "gastrointestinal" },
  { name: "Esomeprazol", presentations: ["40 mg capsula"], therapeuticGroup: "gastrointestinal" },
  { name: "Lansoprazol", presentations: ["30 mg capsula"], therapeuticGroup: "gastrointestinal" },
  { name: "Famotidina", presentations: ["40 mg tableta", "20 mg/2 mL ampolla"], therapeuticGroup: "gastrointestinal" },
  { name: "Ranitidina", presentations: ["150 mg tableta"], therapeuticGroup: "gastrointestinal" },
  { name: "Sucralfato", presentations: ["1 g tableta", "1 g/5 mL suspension"], therapeuticGroup: "gastrointestinal" },
  { name: "Hidroxido de aluminio/magnesio", presentations: ["suspension oral"], therapeuticGroup: "gastrointestinal" },
  { name: "Butilhioscina", presentations: ["10 mg tableta", "20 mg/mL ampolla"], therapeuticGroup: "gastrointestinal" },
  { name: "Ondansetron", presentations: ["8 mg tableta", "8 mg/4 mL ampolla"], therapeuticGroup: "gastrointestinal" },
  { name: "Metoclopramida", presentations: ["10 mg tableta", "10 mg/2 mL ampolla"], therapeuticGroup: "gastrointestinal" },
  { name: "Domperidona", presentations: ["10 mg tableta"], therapeuticGroup: "gastrointestinal" },
  { name: "Dimenhidrinato", presentations: ["50 mg tableta", "50 mg/mL ampolla"], therapeuticGroup: "gastrointestinal" },
  { name: "Loperamida", presentations: ["2 mg capsula"], therapeuticGroup: "gastrointestinal" },
  { name: "Racecadotrilo", presentations: ["100 mg capsula"], therapeuticGroup: "gastrointestinal" },
  { name: "Lactulosa", presentations: ["667 mg/mL jarabe"], therapeuticGroup: "gastrointestinal" },
  { name: "Polietilenglicol", presentations: ["17 g sobre"], therapeuticGroup: "gastrointestinal" },
  { name: "Senosidos", presentations: ["8.6 mg tableta"], therapeuticGroup: "gastrointestinal" },
  { name: "Bisacodilo", presentations: ["5 mg tableta", "10 mg supositorio"], therapeuticGroup: "gastrointestinal" },
  { name: "Mesalazina", presentations: ["500 mg tableta"], therapeuticGroup: "gastrointestinal" },

  { name: "Amoxicilina", presentations: ["500 mg capsula", "250 mg/5 mL suspension"], therapeuticGroup: "antibioticos" },
  { name: "Amoxicilina/Acido clavulanico", presentations: ["875/125 mg tableta", "400/57 mg/5 mL suspension"], therapeuticGroup: "antibioticos" },
  { name: "Ampicilina", presentations: ["500 mg capsula", "1 g vial"], therapeuticGroup: "antibioticos" },
  { name: "Penicilina benzatina", presentations: ["1 200 000 UI vial"], therapeuticGroup: "antibioticos" },
  { name: "Penicilina cristalina", presentations: ["5 000 000 UI vial"], therapeuticGroup: "antibioticos" },
  { name: "Oxacilina", presentations: ["1 g vial"], therapeuticGroup: "antibioticos" },
  { name: "Dicloxacilina", presentations: ["500 mg capsula"], therapeuticGroup: "antibioticos" },
  { name: "Cefalexina", presentations: ["500 mg capsula", "250 mg/5 mL suspension"], therapeuticGroup: "antibioticos" },
  { name: "Cefadroxilo", presentations: ["500 mg capsula"], therapeuticGroup: "antibioticos" },
  { name: "Cefazolina", presentations: ["1 g vial"], therapeuticGroup: "antibioticos" },
  { name: "Cefuroxima", presentations: ["500 mg tableta", "750 mg vial"], therapeuticGroup: "antibioticos" },
  { name: "Cefotaxima", presentations: ["1 g vial"], therapeuticGroup: "antibioticos" },
  { name: "Ceftriaxona", presentations: ["1 g vial", "500 mg vial"], therapeuticGroup: "antibioticos" },
  { name: "Ceftazidima", presentations: ["1 g vial"], therapeuticGroup: "antibioticos" },
  { name: "Cefepime", presentations: ["1 g vial"], therapeuticGroup: "antibioticos" },
  { name: "Meropenem", presentations: ["1 g vial"], therapeuticGroup: "antibioticos" },
  { name: "Imipenem/Cilastatina", presentations: ["500/500 mg vial"], therapeuticGroup: "antibioticos" },
  { name: "Ertapenem", presentations: ["1 g vial"], therapeuticGroup: "antibioticos" },
  { name: "Azitromicina", presentations: ["500 mg tableta", "200 mg/5 mL suspension"], therapeuticGroup: "antibioticos" },
  { name: "Claritromicina", presentations: ["500 mg tableta"], therapeuticGroup: "antibioticos" },

  { name: "Eritromicina", presentations: ["500 mg tableta"], therapeuticGroup: "antibioticos" },
  { name: "Clindamicina", presentations: ["300 mg capsula", "600 mg/4 mL ampolla"], therapeuticGroup: "antibioticos" },
  { name: "Gentamicina", presentations: ["80 mg/2 mL ampolla"], therapeuticGroup: "antibioticos" },
  { name: "Amikacina", presentations: ["500 mg/2 mL ampolla"], therapeuticGroup: "antibioticos" },
  { name: "Tobramicina", presentations: ["80 mg/2 mL ampolla", "0.3% gotas oftalmicas"], therapeuticGroup: "antibioticos" },
  { name: "Ciprofloxacino", presentations: ["500 mg tableta", "200 mg/100 mL infusion"], therapeuticGroup: "antibioticos" },
  { name: "Levofloxacino", presentations: ["500 mg tableta", "500 mg/100 mL infusion"], therapeuticGroup: "antibioticos" },
  { name: "Moxifloxacino", presentations: ["400 mg tableta"], therapeuticGroup: "antibioticos" },
  { name: "Norfloxacino", presentations: ["400 mg tableta"], therapeuticGroup: "antibioticos" },
  { name: "Doxiciclina", presentations: ["100 mg capsula"], therapeuticGroup: "antibioticos" },
  { name: "Tetraciclina", presentations: ["500 mg capsula"], therapeuticGroup: "antibioticos" },
  { name: "Minociclina", presentations: ["100 mg capsula"], therapeuticGroup: "antibioticos" },
  { name: "Metronidazol", presentations: ["500 mg tableta", "500 mg/100 mL infusion"], therapeuticGroup: "antibioticos" },
  { name: "Vancomicina", presentations: ["500 mg vial"], therapeuticGroup: "antibioticos" },
  { name: "Linezolid", presentations: ["600 mg tableta", "600 mg/300 mL infusion"], therapeuticGroup: "antibioticos" },
  { name: "Trimetoprim/Sulfametoxazol", presentations: ["160/800 mg tableta", "40/200 mg/5 mL suspension"], therapeuticGroup: "antibioticos" },
  { name: "Nitrofurantoina", presentations: ["100 mg capsula"], therapeuticGroup: "antibioticos" },
  { name: "Fosfomicina", presentations: ["3 g sobre"], therapeuticGroup: "antibioticos" },
  { name: "Colistina", presentations: ["150 mg vial"], therapeuticGroup: "antibioticos" },
  { name: "Daptomicina", presentations: ["500 mg vial"], therapeuticGroup: "antibioticos" },

  { name: "Fluconazol", presentations: ["150 mg capsula", "200 mg/100 mL infusion"], therapeuticGroup: "antifungicos" },
  { name: "Itraconazol", presentations: ["100 mg capsula"], therapeuticGroup: "antifungicos" },
  { name: "Voriconazol", presentations: ["200 mg tableta", "200 mg vial"], therapeuticGroup: "antifungicos" },
  { name: "Anfotericina B", presentations: ["50 mg vial"], therapeuticGroup: "antifungicos" },
  { name: "Nistatina", presentations: ["100 000 UI/mL suspension", "100 000 UI/g crema"], therapeuticGroup: "antifungicos" },
  { name: "Clotrimazol", presentations: ["1% crema", "500 mg ovulo"], therapeuticGroup: "antifungicos" },
  { name: "Miconazol", presentations: ["2% crema"], therapeuticGroup: "antifungicos" },
  { name: "Ketoconazol", presentations: ["200 mg tableta", "2% shampoo"], therapeuticGroup: "antifungicos" },
  { name: "Terbinafina", presentations: ["250 mg tableta", "1% crema"], therapeuticGroup: "antifungicos" },
  { name: "Aciclovir", presentations: ["400 mg tableta", "250 mg vial", "5% crema"], therapeuticGroup: "antivirales" },
  { name: "Valaciclovir", presentations: ["500 mg tableta"], therapeuticGroup: "antivirales" },
  { name: "Oseltamivir", presentations: ["75 mg capsula"], therapeuticGroup: "antivirales" },
  { name: "Tenofovir", presentations: ["300 mg tableta"], therapeuticGroup: "antivirales" },
  { name: "Lamivudina", presentations: ["150 mg tableta"], therapeuticGroup: "antivirales" },
  { name: "Dolutegravir", presentations: ["50 mg tableta"], therapeuticGroup: "antivirales" },
  { name: "Efavirenz", presentations: ["600 mg tableta"], therapeuticGroup: "antivirales" },
  { name: "Emtricitabina/Tenofovir", presentations: ["200/300 mg tableta"], therapeuticGroup: "antivirales" },
  { name: "Lamivudina/Zidovudina", presentations: ["150/300 mg tableta"], therapeuticGroup: "antivirales" },
  { name: "Rifampicina", presentations: ["300 mg capsula"], therapeuticGroup: "antituberculosos" },
  { name: "Isoniazida", presentations: ["100 mg tableta"], therapeuticGroup: "antituberculosos" },

  { name: "Pirazinamida", presentations: ["500 mg tableta"], therapeuticGroup: "antituberculosos" },
  { name: "Etambutol", presentations: ["400 mg tableta"], therapeuticGroup: "antituberculosos" },
  { name: "Levetiracetam", presentations: ["500 mg tableta", "500 mg/5 mL ampolla"], therapeuticGroup: "neurologicos" },
  { name: "Acido valproico", presentations: ["500 mg tableta", "250 mg/5 mL jarabe"], therapeuticGroup: "neurologicos" },
  { name: "Carbamazepina", presentations: ["200 mg tableta"], therapeuticGroup: "neurologicos" },
  { name: "Lamotrigina", presentations: ["100 mg tableta"], therapeuticGroup: "neurologicos" },
  { name: "Fenitoina", presentations: ["100 mg capsula", "250 mg/5 mL ampolla"], therapeuticGroup: "neurologicos" },
  { name: "Fenobarbital", presentations: ["100 mg tableta", "200 mg/mL ampolla"], therapeuticGroup: "neurologicos" },
  { name: "Topiramato", presentations: ["50 mg tableta"], therapeuticGroup: "neurologicos" },
  { name: "Lacosamida", presentations: ["100 mg tableta"], therapeuticGroup: "neurologicos" },
  { name: "Diazepam", presentations: ["10 mg tableta", "10 mg/2 mL ampolla"], therapeuticGroup: "neurologicos" },
  { name: "Lorazepam", presentations: ["2 mg tableta", "4 mg/mL ampolla"], therapeuticGroup: "neurologicos" },
  { name: "Clonazepam", presentations: ["2 mg tableta", "2.5 mg/mL gotas"], therapeuticGroup: "neurologicos" },
  { name: "Midazolam", presentations: ["5 mg/mL ampolla"], therapeuticGroup: "neurologicos" },
  { name: "Alprazolam", presentations: ["0.5 mg tableta"], therapeuticGroup: "neurologicos" },
  { name: "Sertralina", presentations: ["50 mg tableta"], therapeuticGroup: "psiquiatricos" },
  { name: "Fluoxetina", presentations: ["20 mg capsula"], therapeuticGroup: "psiquiatricos" },
  { name: "Escitalopram", presentations: ["10 mg tableta"], therapeuticGroup: "psiquiatricos" },
  { name: "Paroxetina", presentations: ["20 mg tableta"], therapeuticGroup: "psiquiatricos" },
  { name: "Venlafaxina", presentations: ["75 mg capsula"], therapeuticGroup: "psiquiatricos" },

  { name: "Duloxetina", presentations: ["60 mg capsula"], therapeuticGroup: "psiquiatricos" },
  { name: "Bupropion", presentations: ["150 mg liberacion prolongada"], therapeuticGroup: "psiquiatricos" },
  { name: "Mirtazapina", presentations: ["30 mg tableta"], therapeuticGroup: "psiquiatricos" },
  { name: "Quetiapina", presentations: ["100 mg tableta"], therapeuticGroup: "psiquiatricos" },
  { name: "Risperidona", presentations: ["2 mg tableta", "1 mg/mL solucion"], therapeuticGroup: "psiquiatricos" },
  { name: "Olanzapina", presentations: ["10 mg tableta"], therapeuticGroup: "psiquiatricos" },
  { name: "Haloperidol", presentations: ["5 mg tableta", "5 mg/mL ampolla"], therapeuticGroup: "psiquiatricos" },
  { name: "Clozapina", presentations: ["100 mg tableta"], therapeuticGroup: "psiquiatricos" },
  { name: "Aripiprazol", presentations: ["10 mg tableta"], therapeuticGroup: "psiquiatricos" },
  { name: "Litio carbonato", presentations: ["300 mg tableta"], therapeuticGroup: "psiquiatricos" },
  { name: "Benztropina", presentations: ["2 mg tableta"], therapeuticGroup: "neurologicos" },
  { name: "Biperideno", presentations: ["2 mg tableta", "5 mg/mL ampolla"], therapeuticGroup: "neurologicos" },
  { name: "Levodopa/Carbidopa", presentations: ["250/25 mg tableta"], therapeuticGroup: "neurologicos" },
  { name: "Pramipexol", presentations: ["0.5 mg tableta"], therapeuticGroup: "neurologicos" },
  { name: "Donepezilo", presentations: ["10 mg tableta"], therapeuticGroup: "neurologicos" },
  { name: "Memantina", presentations: ["10 mg tableta"], therapeuticGroup: "neurologicos" },
  { name: "Sumatriptan", presentations: ["50 mg tableta", "6 mg/0.5 mL autoinyector"], therapeuticGroup: "neurologicos" },
  { name: "Rizatriptan", presentations: ["10 mg tableta"], therapeuticGroup: "neurologicos" },
  { name: "Proclorperazina", presentations: ["10 mg tableta"], therapeuticGroup: "neurologicos" },
  { name: "Piracetam", presentations: ["800 mg tableta"], therapeuticGroup: "neurologicos" },

  { name: "Oxitocina", presentations: ["10 UI/mL ampolla"], therapeuticGroup: "obstetricos" },
  { name: "Misoprostol", presentations: ["200 mcg tableta"], therapeuticGroup: "obstetricos" },
  { name: "Sulfato de magnesio", presentations: ["20% ampolla"], therapeuticGroup: "obstetricos" },
  { name: "Metilergonovina", presentations: ["0.2 mg/mL ampolla"], therapeuticGroup: "obstetricos" },
  { name: "Nifedipino tocolitico", presentations: ["10 mg capsula"], therapeuticGroup: "obstetricos" },
  { name: "Atosiban", presentations: ["7.5 mg/mL ampolla"], therapeuticGroup: "obstetricos" },
  { name: "Betametasona prenatal", presentations: ["12 mg/2 mL ampolla"], therapeuticGroup: "obstetricos" },
  { name: "Progesterona", presentations: ["200 mg capsula vaginal"], therapeuticGroup: "obstetricos" },
  { name: "Medroxiprogesterona", presentations: ["150 mg/mL inyectable"], therapeuticGroup: "obstetricos" },
  { name: "Etinilestradiol/Levonorgestrel", presentations: ["0.03/0.15 mg tableta"], therapeuticGroup: "obstetricos" },
  { name: "Levonorgestrel", presentations: ["1.5 mg tableta"], therapeuticGroup: "obstetricos" },
  { name: "Acido tranexamico", presentations: ["500 mg tableta", "500 mg/5 mL ampolla"], therapeuticGroup: "hematologicos" },
  { name: "Tamsulosina", presentations: ["0.4 mg capsula"], therapeuticGroup: "urologicos" },
  { name: "Finasterida", presentations: ["5 mg tableta"], therapeuticGroup: "urologicos" },
  { name: "Dutasterida", presentations: ["0.5 mg capsula"], therapeuticGroup: "urologicos" },
  { name: "Oxibutinina", presentations: ["5 mg tableta"], therapeuticGroup: "urologicos" },
  { name: "Tolterodina", presentations: ["2 mg tableta"], therapeuticGroup: "urologicos" },
  { name: "Sildenafilo", presentations: ["50 mg tableta"], therapeuticGroup: "urologicos" },
  { name: "Tadalafil", presentations: ["5 mg tableta"], therapeuticGroup: "urologicos" },
  { name: "Nitroprusiato de sodio", presentations: ["50 mg vial"], therapeuticGroup: "cardiovasculares" },

  { name: "Epinefrina", presentations: ["1 mg/mL ampolla", "0.3 mg autoinyector"], therapeuticGroup: "emergencias" },
  { name: "Norepinefrina", presentations: ["4 mg/4 mL ampolla"], therapeuticGroup: "emergencias" },
  { name: "Dopamina", presentations: ["200 mg/5 mL ampolla"], therapeuticGroup: "emergencias" },
  { name: "Dobutamina", presentations: ["250 mg/20 mL ampolla"], therapeuticGroup: "emergencias" },
  { name: "Atropina", presentations: ["1 mg/mL ampolla"], therapeuticGroup: "emergencias" },
  { name: "Naloxona", presentations: ["0.4 mg/mL ampolla"], therapeuticGroup: "emergencias" },
  { name: "Flumazenil", presentations: ["0.5 mg/5 mL ampolla"], therapeuticGroup: "emergencias" },
  { name: "Glucagon", presentations: ["1 mg vial"], therapeuticGroup: "emergencias" },
  { name: "Mannitol", presentations: ["20% 250 mL bolsa"], therapeuticGroup: "emergencias" },
  { name: "Bicarbonato de sodio", presentations: ["8.4% ampolla"], therapeuticGroup: "emergencias" },
  { name: "Calcio gluconato", presentations: ["10% ampolla"], therapeuticGroup: "emergencias" },
  { name: "Cloruro de potasio", presentations: ["2 mEq/mL ampolla"], therapeuticGroup: "emergencias" },
  { name: "Sulfato de zinc oral", presentations: ["20 mg tableta"], therapeuticGroup: "suplementos" },
  { name: "Solucion salina 0.9%", presentations: ["500 mL bolsa", "1000 mL bolsa"], therapeuticGroup: "soluciones" },
  { name: "Ringer lactato", presentations: ["500 mL bolsa", "1000 mL bolsa"], therapeuticGroup: "soluciones" },
  { name: "Dextrosa 5%", presentations: ["500 mL bolsa"], therapeuticGroup: "soluciones" },
  { name: "Dextrosa 10%", presentations: ["500 mL bolsa"], therapeuticGroup: "soluciones" },
  { name: "Dextrosa 50%", presentations: ["50 mL ampolla"], therapeuticGroup: "soluciones" },
  { name: "Solucion Hartmann", presentations: ["1000 mL bolsa"], therapeuticGroup: "soluciones" },
  { name: "Albumina humana", presentations: ["20% 50 mL frasco"], therapeuticGroup: "soluciones" },

  { name: "Mupirocina", presentations: ["2% ungueento"], therapeuticGroup: "topicos" },
  { name: "Acido fusidico", presentations: ["2% crema"], therapeuticGroup: "topicos" },
  { name: "Sulfadiazina de plata", presentations: ["1% crema"], therapeuticGroup: "topicos" },
  { name: "Neomicina/Bacitracina", presentations: ["ungueento topico"], therapeuticGroup: "topicos" },
  { name: "Gentamicina topica", presentations: ["0.1% crema"], therapeuticGroup: "topicos" },
  { name: "Povidona yodada", presentations: ["10% solucion"], therapeuticGroup: "topicos" },
  { name: "Clorhexidina", presentations: ["2% solucion"], therapeuticGroup: "topicos" },
  { name: "Permetrina", presentations: ["5% crema"], therapeuticGroup: "topicos" },
  { name: "Hidrocortisona topica", presentations: ["1% crema"], therapeuticGroup: "topicos" },
  { name: "Betametasona topica", presentations: ["0.05% crema"], therapeuticGroup: "topicos" },
  { name: "Diclofenaco topico", presentations: ["1% gel"], therapeuticGroup: "topicos" },
  { name: "Ketoprofeno topico", presentations: ["2.5% gel"], therapeuticGroup: "topicos" },
  { name: "Lidocaina topica", presentations: ["5% gel"], therapeuticGroup: "topicos" },
  { name: "Acido salicilico", presentations: ["17% solucion"], therapeuticGroup: "topicos" },
  { name: "Urea topica", presentations: ["20% crema"], therapeuticGroup: "topicos" },
  { name: "Timolol oftalmico", presentations: ["0.5% gotas"], therapeuticGroup: "oftalmicos" },
  { name: "Latanoprost", presentations: ["0.005% gotas"], therapeuticGroup: "oftalmicos" },
  { name: "Brimonidina", presentations: ["0.2% gotas"], therapeuticGroup: "oftalmicos" },
  { name: "Carboximetilcelulosa", presentations: ["gotas oftalmicas lubricantes"], therapeuticGroup: "oftalmicos" },
  { name: "Tobramicina oftalmica", presentations: ["0.3% gotas"], therapeuticGroup: "oftalmicos" },

  { name: "Pilocarpina", presentations: ["2% gotas oftalmicas"], therapeuticGroup: "oftalmicos" },
  { name: "Dorzolamida", presentations: ["2% gotas oftalmicas"], therapeuticGroup: "oftalmicos" },
  { name: "Ciprofloxacino oftalmico", presentations: ["0.3% gotas"], therapeuticGroup: "oftalmicos" },
  { name: "Moxifloxacino oftalmico", presentations: ["0.5% gotas"], therapeuticGroup: "oftalmicos" },
  { name: "Prednisolona oftalmica", presentations: ["1% gotas"], therapeuticGroup: "oftalmicos" },
  { name: "Difenhidramina", presentations: ["25 mg capsula", "50 mg/mL ampolla"], therapeuticGroup: "alergias" },
  { name: "Clorfenamina", presentations: ["4 mg tableta", "10 mg/mL ampolla"], therapeuticGroup: "alergias" },
  { name: "Cetirizina", presentations: ["10 mg tableta", "5 mg/5 mL jarabe"], therapeuticGroup: "alergias" },
  { name: "Loratadina", presentations: ["10 mg tableta", "5 mg/5 mL jarabe"], therapeuticGroup: "alergias" },
  { name: "Desloratadina", presentations: ["5 mg tableta"], therapeuticGroup: "alergias" },
  { name: "Fexofenadina", presentations: ["120 mg tableta"], therapeuticGroup: "alergias" },
  { name: "Hidroxicina", presentations: ["25 mg tableta", "2 mg/mL jarabe"], therapeuticGroup: "alergias" },
  { name: "Montelukast pediatrico", presentations: ["4 mg granulado"], therapeuticGroup: "alergias" },
  { name: "Colchicina", presentations: ["0.5 mg tableta"], therapeuticGroup: "reumatologicos" },
  { name: "Alopurinol", presentations: ["300 mg tableta"], therapeuticGroup: "reumatologicos" },
  { name: "Febuxostat", presentations: ["40 mg tableta"], therapeuticGroup: "reumatologicos" },
  { name: "Hidroxicloroquina", presentations: ["200 mg tableta"], therapeuticGroup: "reumatologicos" },
  { name: "Sulfasalazina", presentations: ["500 mg tableta"], therapeuticGroup: "reumatologicos" },
  { name: "Metotrexato", presentations: ["2.5 mg tableta", "50 mg/2 mL ampolla"], therapeuticGroup: "reumatologicos" },
  { name: "Azatioprina", presentations: ["50 mg tableta"], therapeuticGroup: "inmunologicos" },
  { name: "Ciclosporina", presentations: ["100 mg capsula"], therapeuticGroup: "inmunologicos" },
  { name: "Tacrolimus", presentations: ["1 mg capsula", "0.1% ungueento"], therapeuticGroup: "inmunologicos" },
  { name: "Micofenolato mofetilo", presentations: ["500 mg tableta"], therapeuticGroup: "inmunologicos" },
  { name: "Sirolimus", presentations: ["1 mg tableta"], therapeuticGroup: "inmunologicos" },
];

const medicationCatalogSeed = [
  ...baseMedicationCatalogSeed,
  ...buildPresentationCatalogRows(baseMedicationCatalogSeed),
];

export const medicationCatalogBase = medicationCatalogSeed;
export const medicationCatalogTotal = medicationCatalogSeed.length;

function buildPresentationCatalogRows(items: MedicationCatalogItem[]) {
  return items.flatMap((item) =>
    item.presentations.map((presentation) => ({
      name: `${item.name} · ${presentation}`,
      presentations: [presentation],
      therapeuticGroup: item.therapeuticGroup,
    }))
  );
}
